### ISSUE TITLE
QA design checklist

### ISSUE THREAD

**Issue by kristinashu** [mozilla/ihr-landing-site#6]
### Pre-launch checklist for design QA:

- [x] Staging: https://healthreport.staging.wpengine.com/ (timeframe July 10-13)
- [x] Production (need to add URL) (timeframe Aug)

### Check on latest version of (marked with *)
- [x] Firefox for Mac
- [x] Chrome for Mac
- [x] Safari for Mac
- [x] Opera for Mac
- [ ] Firefox for Windows
- [ ] Chrome for Windows
- [ ] Safari for Windows
- [ ] Microsoft Edge for Windows
- [ ] Opera for Windows
- [ ] iPad (FF, Chrome, and Safari)
- [x] iPhone (FF, Chrome, and Safari)
- [ ] Android tablet (different browsers?)
- [ ] Android phone (different browsers?)

### Design review ([compare with comps](https://redpen.io/p/zj2a11a1dd21b0d7d3))
- [x] All fonts and images are loading
- [x] Resize the browser for responsiveness
- [x] Fav icon
- [x] Links and buttons have hover states
- [x] Nav: 
    - logo links to home
    - Blog, About, Contribute/Feedback link correctly
    - WPML translation plugin design
- [x] Footer links (including RSS feed)*

### Newsletter signup forms (can use example.com to test)
- [x] As a user, enter your email and confirm you received an email (use yourname+testname@mozillafoundation.org to properly test - you will receive an email at yourname@mozillafoundation.org and the +testname will show up uniquely in Salesforce)
- [x] To test the proper URL is sent to Salesforce: As a user, go to URL/?r=test (e.g. https://healthreport.staging.wpengine.com/?r=test) enter your email (e.g. yourname+testURL@mozillafoundation.org) and confirm you received an email
- [x] As a Mozilla Salesforce admin, confirm the user’s email was added to Salesforce from the correct URL (both regular and /?r=test)
- [ ] As a user, check error messages (no email, checkbox not ticked)*

### Individual Pages
- [x] Home 
    - Hero banner with link to About page
    - 2 feature boxes with links
    - Blog features with links
- [x] Blog overview
    - Featured post
    - Most recent posts at the top
    - Load more button
    - Category filters
    - Search - test several search terms
- [x] Blog detail
    - Title, author, date, category, annotation link opens sidebar, comment link scrolls user down the page
    - Related posts
    - Video embed, image with caption, quote
    - FB and twitter share functionality
    - wpDiscuz commenting plugin: post a test comment*
    - hypothes.is annotation plugin: post a test note and annotate*
- [x] About
    - Text
    - CTA link scrolls down to newsletter signup form
    - Timeline
    - Archives (post-launch)
- [x] Feedback: iFrame from Coral Project loads and works

### Content
- [x] Check for content and spelling on all pages (Home, Blog, Blog detail views, About, Feedback)

### Localization (post-launch)
- [ ] Fluent speaker to check content and spelling for each available language
- [ ] Fluent speaker to check date formats
- [x] Designer to check if design breaks (long words…)
- [x] Design to check that font loads

### Analytics, SEO, URLs and redirects:
- [x] Landing site lives on http://internethealthreport.org/
- [x] https://internethealthreport.org/v01/ no longer redirects http://internethealthreport.org/
- [x] Check that subpage URLs makes sense
- [x] Redirect non-www to www (?)
- [x] Check the 404 page, make sure it redirects to 404
- [x] Google Analytics
- [ ] Check google search results title and description

### Accessibility
- [x] Site load-time is reasonable (images are optimized...)
- [x] Adequate text-to-background contrast http://www.checkmycolours.com/
- [x] Font size and line height are easy to read
- [x] Images have appropriate alt tags
- [x] Test in https://achecker.ca/checker/index.php (?)

### Easy to update and add CMS content
- [x] Home 
    - Hero banner (title, body, link, image)
    - 2 feature boxes (title, body, link, image)
    - Blog features (checkbox to feature post)
- [x] Blog
    - Select featured post
    - Add new post (title, author, date, category, tags, thumbnail, intro text, body text, video embed, image with caption, quote)
- [x] About
    - Tagline, intro, and body text
    - Update Timeline
    - Archives
